# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADVGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_jarvis(object):
    def setupUi(self, jarvis):
        jarvis.setObjectName("jarvis")
        jarvis.resize(1410, 845)
        self.centralwidget = QtWidgets.QWidget(jarvis)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, -60, 1601, 921))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/B.G/Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 130, 731, 541))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/B.G/Iron_Template_1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, -80, 421, 301))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/extGUI/initial.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(970, 10, 501, 301))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/extGUI/Jarvis_Gui (1).gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 391, 201))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/extGUI/B.G_Template_1.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-20, 530, 401, 241))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/extGUI/Earth_Template.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(940, 410, 601, 471))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/voisrec/Siri_1.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(560, 610, 401, 71))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/shubhu rajput/python26/GUI/extGUI/load-loading.gif"))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 740, 121, 51))
        self.pushButton.setStyleSheet("color: rgb(0, 170, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0,0,0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(750, 740, 121, 51))
        self.pushButton_2.setStyleSheet("color: rgb(0, 170, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        jarvis.setCentralWidget(self.centralwidget)

        self.retranslateUi(jarvis)
        QtCore.QMetaObject.connectSlotsByName(jarvis)

    def retranslateUi(self, jarvis):
        _translate = QtCore.QCoreApplication.translate
        jarvis.setWindowTitle(_translate("jarvis", "MainWindow"))
        self.pushButton.setText(_translate("jarvis", "START"))
        self.pushButton_2.setText(_translate("jarvis", "QUITE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    jarvis = QtWidgets.QMainWindow()
    ui = Ui_jarvis()
    ui.setupUi(jarvis)
    jarvis.show()
    sys.exit(app.exec_())
